blog/urls.py
#blog urls
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name = 'blog'),
    url(r'^view/(?P<slug>[^\.]+).html', views.PostView.as_view(), name='view_post'),
    url(r'^category/(?P<slug>[^\.]+).html', views.CategoryView.as_view(), name='view_category'),
    url(r'^tag/(?P<slug>[^\.]+).html', views.TagView.as_view(), name='view_tag'),
    url(r'^new/', views.post_new, name='post_new'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
]

futulink/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import home, home_files

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace = 'polls')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^$', home, name='home'),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$', home_files, name='home-files'),
    url(r'^summernote/', include('django_summernote.urls')),

]

blog/models.py
#blog models
from django.db import models
from django.db.models import permalink
from django.utils import timezone

class Post(models.Model):
    author = models.ForeignKey('auth.User')
    title = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(max_length=100, unique=True)
    body = models.TextField()
    posted = models.DateTimeField(db_index=True, auto_now_add=True)
    published_date = models.DateTimeField(blank=True, null=True)
    category = models.ForeignKey('blog.Category')
    tags = models.ManyToManyField('blog.Tag')

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __unicode__(self):
        return '%s' % self.title

    def __str__(self):
        return self.slug

    @permalink
    def get_absolute_url(self):
        return ('blog:view_post', None, { 'slug': self.slug })

class Category(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __unicode__(self):
        return '%s' % self.title

    def __str__(self):
        return self.slug

    @permalink
    def get_absolute_url(self):
        return ('blog:view_category', None, { 'slug': self.slug })

class Tag(models.Model):
    title = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)

    def __str__(self):
        return self.slug

    @permalink
    def get_absolute_url(self):
        return ('blog:view_tag', None, { 'slug': self.slug })

class Comment(models.Model):
    post = models.ForeignKey('blog.Post', related_name='comments')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

    def approve(self):
        self.approved = True
        self.save()

    def __str__(self):
        return self.text

    def approved_comments(self):
        return self.comments.filter(approved=True)

blog/forms.py
from django import forms
from .models import Post, Comment, Tag
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ('title', 'slug', 'category', 'tags', 'body')
        
        widgets = {'body': SummernoteWidget(), 'tags': forms.CheckboxSelectMultiple}

class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('author', 'text',)

blog/views.py
from .models import Post, Category, Tag, Comment
from .forms import PostForm, CommentForm
from django.shortcuts import render_to_response, get_object_or_404, render, redirect
from django.views import generic
from django.core.urlresolvers import reverse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django import forms


class BlogIndex(generic.ListView):
    template_name = 'blog/index.html'
    context_object_name = 'latest_post_list'
    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Post.objects.order_by('-posted')[:5]

class PostView(generic.DetailView):
    template_name = 'blog/post.html'
    model = Post
    def get_queryset(self):
        return Post.objects

class CategoryView(generic.DetailView):
    template_name = 'blog/category.html'
    model = Category
    def get_queryset(self):
        return Category.objects

class TagView(generic.DetailView):
    template_name = 'blog/tag.html'
    model = Tag
    def get_queryset(self):
        return Tag.objects

@login_required
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        slug=request.POST.get('slug','')
        tags = request.POST.getlist('tags','')
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user

              
            #post.published_date = timezone.now()
            post.save()
            for tag in tags:
                post.tags.add(tag)
            return redirect(post)
    else:
        form = PostForm()
    return render(request, 'blog/post_edit.html', {'form': form})

def detail(request):
    post = PostView(request)
    return post.as_view()

def post_draft_list(request):
    posts = Post.objects.filter(published_date__isnull=True).order_by('posted')
    return render(request, 'blog/post_draft_list.html', {'posts': posts})


def post_publish(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect(post)

def post_remove(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('blog:blog')

def add_comment_to_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect(post)
    else:
        form = CommentForm()
    return render(request, 'blog/add_comment_to_post.html', {'form': form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = get_object_or_404(Post, pk=comment.post.pk)
    comment.approve()
    return redirect(post)

@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = get_object_or_404(Post, pk=comment.post.pk)
    post_pk = comment.post.pk
    comment.delete()
    return redirect(post)




#def blog(request):
#    latest_post_list = Question.objects.order_by('-posted')[:5]
#    context = {'latest_post_list': latest_post_list}
#    return render(request, 'blog/index.html', context)

#def view_post(request, slug):
#    current_post = get_object_or_404(Blog, slug=slug)
#    context = {'current_post': current_post}
    #return render(request, 'blog/post.html', context)

#def view_category(request, slug):
#    category = get_object_or_404(Category, slug=slug)
#    context = {'category':category}
#    return render(request, 'blog/category.html', context)

templates/blog/add_comment_to_post.html
{% extends 'base.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

templates/blog/category.html
{% extends 'base.html' %} 
{% block head_title %}{{ category.title }}{% endblock %}

{% block content %}
    <h2> {{ category.title }} </h2>
    {{ category.slug }}
{% endblock %}

templates/blog/index.html
{% extends 'base.html' %}
{% block head_title %}Welcome to my blog{% endblock %}

{% block content %}
    <div>
        <h2>Posts<a href="{% url 'blog:post_new' %}"><span class="glyphicon glyphicon-file"></span></a>
        <a href="{% url 'blog:post_draft_list' %}" class="top-menu"><span class="glyphicon glyphicon-edit"></span></a>
        </h2>
    </div>
    {% if latest_post_list %}
        <ul>
        {% for post in latest_post_list %}
            <li><a href="{% url 'blog:view_post' post.slug %}">{{ post.title }} Comments: {{ post.comments.count }}</a>
            <a href="{% url 'blog:view_category' post.category.slug %}">{{ post.category.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}

    <h2>Categories</h2>

{% endblock %}

templates/blog/post.html
{% extends 'blog_base.html' %} 
{% block head_title %}{{ post.title }}{% endblock %}

{% block content %}
    <h2> {{ post.title }} {{ post.category.title }} 
        <a class="btn btn-default" href="{% url 'blog:post_remove' pk=post.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
    </h2>
    {% for tag in post.tags.all %}
    {{ tag.title }}
    {% empty %}
        <p>No tags here :(</p>
    {% endfor%}
    <div>
        {{ post.body|safe }}
    </div>
    {% if post.published_date %}
        {{ post.published_date }}
    {% else %}
        <a class="btn btn-default" href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
    {% endif %}

    <hr>
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved %}
        <div class="comment">
            <div class="date">
                {{ comment.created_date }}
                {% if not comment.approved %}
                    <a class="btn btn-default" href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
                    <a class="btn btn-default" href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok"></span></a>
                {% endif %}
            </div>
            <strong>{{ comment.author }}</strong>
            <p>{{ comment.text|linebreaks }}</p>
        </div>
        {% endif %}
    {% empty %}
        <p>No comments here yet :(</p>
    {% endfor %}
    <a class="btn btn-default" href="{% url 'blog:add_comment_to_post' pk=post.pk %}">Add comment</a>

{% endblock %}

templates/blog/post_draft_list.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <p class="date">created: {{ post.posted|date:'d-m-Y' }}</p>
            <h1><a href="{% url 'blog:view_post' post.slug %}">{{ post.title }}</a></h1>
            <p>{{ post.text|truncatechars:200 }}</p>
        </div>
    {% endfor %}
{% endblock %}

templates/blog/post_edit.html
{% extends "base.html" %}

{% block content %}
    {% load widget_tweaks %}
    <div class="container">
    <h1>New post</h1>
    <form method="POST" class="form-inline">{% csrf_token %}
    <div class="container">
        <div class="form-group">
        {% render_field form.title class+="form-control" autofocus="" required="" placeholder="Title" %}
        {% render_field form.slug class+="form-control" autofocus="" required="" placeholder="Slug" %}
        </div> 
        <div class="form-group">
        {{ form.category }}
        </div> 
        <div class="form-group">
        {{ form.tags }}
        </div>
        <button type="submit" class="btn btn-lg btn-success">Save</button>
    </div>
        {{ form.body|safe }}
        
    </form>
    </div>
{% endblock %}

templates/blog/tag.html
{% extends 'base.html' %} 
{% block head_title %}{{ tag.title }}{% endblock %}

{% block content %}
    <h2> {{ tag.title }} </h2>
    {{ tag.slug }}
{% endblock %}