blog/urls.py
#blog urls
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.BlogIndex.as_view(), name = 'blog'),
    url(r'^view/(?P<slug>[^\.]+).html', views.PostView.as_view(), name='view_post'),
    url(r'^category/(?P<slug>[^\.]+).html', views.CategoryView.as_view(), name='view_category'),
    url(r'^tag/(?P<slug>[^\.]+).html', views.TagView.as_view(), name='view_tag'),
    url(r'^new/', views.post_new, name='post_new'),
    url(r'^drafts/$', views.post_draft_list, name='post_draft_list'),
    url(r'^post/(?P<pk>[0-9]+)/remove/$', views.post_remove, name='post_remove'),
    url(r'^post/(?P<pk>[0-9]+)/publish/$', views.post_publish, name='post_publish'),
    url(r'^post/(?P<pk>[0-9]+)/comment/$', views.add_comment_to_post, name='add_comment_to_post'),
    url(r'^comment/(?P<pk>[0-9]+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>[0-9]+)/remove/$', views.comment_remove, name='comment_remove'),
]

futulink/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from .views import home, home_files

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace = 'polls')),
    url(r'^blog/', include('blog.urls', namespace = 'blog')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}),
    url(r'^$', home, name='home'),
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$', home_files, name='home-files'),
    url(r'^summernote/', include('django_summernote.urls')),

]

templates/base.html
{% load staticfiles %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang=""> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block head_title %}{% endblock %}</title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="apple-touch-icon" href="{% static 'apple-touch-icon.png' %}">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <style>
            body {
                padding-top: 0px;
                padding-bottom: 0px;
            }
          .affix {
              top: 0;
              width: 100%;
          }

          .affix + .container{
              padding-top: 70px;
          }
        </style>
        <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        <link rel="shortcut icon" href="{% static 'favicon.ico' %}" type="image/x-icon">

        <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
        {% block head_css %}{% endblock %}
        {% block head_javascript %}{% endblock %}
    </head>
    <body>
        <!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
    {% block navbar %}
    <div class="container-fluid" style="background-color:#F44336;color:#fff;height:200px;">
      <h1>Bootstrap Affix Example</h1>
      <h3>Fixed (sticky) navbar on scroll</h3>
      <p>Scroll this page to see how the navbar behaves with data-spy="affix".</p>
      <p>The navbar is attached to the top of the page after you have scrolled a specified amount of pixels.</p>
    </div>
    <div id="nav-wrapper" data-spy="affix" data-offset-top="197">
        <div id="nav" class="navbar navbar-default" >
          <div class="container">
            <div class="navbar-header">
     
              <a class="navbar-brand" href="{% url 'home' %}">FutuLink</a>
            </div>
       
            <ul class="nav navbar-nav">
            <li class="hidden-xs {% if request.path == '/' %}active{% endif %}">
                <a href="{% url 'home' %}">Home</a>
            </li>
            <li class="hidden-xs {% if '/blog/' in request.path %}active{% endif %}">
                <a href="{% url 'blog:blog' %}">Blog</a>
            </li>
            <li class="hidden-xs">
                <a href="#contact">Contact</a>
            </li>
            <li>
            {% if user.is_authenticated %}
            <a href="{% url 'django.contrib.auth.views.logout' %}">Sign out</a>
            {% else %}
            <a href="{% url 'django.contrib.auth.views.login' %}" class="top-menu">Sign in</span></a>
            {% endif %}
            </li>
            </ul>
            </div>  
            </div><!--/.navbar-collapse -->
          </div>
        </div>
    </div>
    {% endblock %}
    
    <div class="container">
      <div class="row" style="border-bottom-width:1px">
        <div id="row-header" class="col-sm-8">
          {% block header_left %}
            <h1>Some long text for different pages of website</h1>
          {% endblock %}
        </div>
  
        <div id="row-header" class="col-sm-3 hidden-xs">
          {% block header_right %}
            <p>Right menu header with picture for page types</p>
          {% endblock %}
        </div>
      </div>
      <div class="row-fluid">
        <div class="col-sm-9">          
          {% block content %}
          {% endblock %}
        </div>
        <div class="col-sm-3">
          {% block sidebar %}
          {% endblock %}
        </div>
      </div>
    </div>
    
</div> <!-- /container --> 
     <hr>

      <footer>
        <p>&copy; Company 2015</p>
      </footer>
           <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="static/js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

        <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>

        {% block footer_javascript %}{% endblock %}

        <!-- Google Analytics: change UA-XXXXX-X to be your site's ID. -->
        <script>
            (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
            function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
            e=o.createElement(i);r=o.getElementsByTagName(i)[0];
            e.src='//www.google-analytics.com/analytics.js';
            r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
            ga('create','UA-XXXXX-X','auto');ga('send','pageview');
        </script>
    </body>
</html>

templates/blog_base.html
{% extends 'base.html' %}

{% block sidebar %} here will some elements {% endblock %}